name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3    
      with:
        fetch-depth: 0
    # nuevospasso
    - name: nombreCualqueira login
    # aqui_se_usa_la_variable_creada_en_github_secrets
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWOR: ${{ secrets.DOCKER_USER }}
        #aqui_Se_pone_lo_que_Se_va_correr
      run: |
        #Indica_que_se_van_agregar_Muchas_instrucciones_y_que_cada_una_va_ser_independiente
        echo "iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_USER
        echo "Fin de login"
